### ISSUE TITLE
Change argument eps_user to eps

### ISSUE THREAD

**Issue by dongli** [dongli/fortran-unit-test#12]
Argument `eps` may be more intuitive to users.

**Comment by JHenneberg** [comment]
Probably it is. I just changed it because I implemented a global default eps. 
    
` eps = merge(eps_user, eps_default_kind8, present(eps_user))`

of course we can get rid of this by just not storing the result in a local variable instead use it like you implemented it in the line where it is needed although the line would be getting much longer. 
` if (.not. abs(x(i, j) - y(i, j)) / get_relative_difference(x(i, j), y(i, j)) < eps) then`
For me it is not important. So you change it the way you like :)

**Comment by dongli** [comment]
See fa807426bcbb7952c96cd02f1b5f1b9d365f699e.
